### ISSUE TITLE
Buld finish with no binaries

### ISSUE THREAD

**Issue by rorlich** [ElfSundae/FFmpeg-iOS-build#2]
[log.txt](https://github.com/ElfSundae/FFmpeg-iOS-build/files/434138/log.txt)

build finish after ~2min but no binaries could be found

ffmpeg-2.0.1/lib is empty
libx264 is empty

**Comment by ElfSundae** [comment]
Have you configured the SDK version in `make.php` ?

After 3 years, many things changed, this script may be broken, and I will update it later.

**Comment by rorlich** [comment]
Yes, i changed the version to 3.0.0 but it didn't work for 2.0.1 as well..

**Comment by ElfSundae** [comment]
The `$ios_sdk_version` should be the same as your Xcode version.

**Comment by ElfSundae** [comment]
OK, this script will not be work, it should be deprecated.
You can try https://github.com/kewlbear/FFmpeg-iOS-build-script
